//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitMind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goodie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goodie()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int goodieId { get; set; }
        public string description { get; set; }
        public Nullable<int> pointsNeeded { get; set; }
        public string category { get; set; }
        public Nullable<int> sponsorId { get; set; }
    
        public virtual Sponsor Sponsor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
