//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitMind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionId { get; set; }
        public Nullable<System.DateTime> claimDate { get; set; }
        public Nullable<System.DateTime> redeemDate { get; set; }
        public Nullable<bool> redeemed { get; set; }
        public Nullable<int> goodieId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Goodie Goodie { get; set; }
        public virtual User User { get; set; }
    }
}
