//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitMind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuiz
    {
        public int userQuizId { get; set; }
        public Nullable<bool> complete { get; set; }
        public Nullable<int> quizId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual User User { get; set; }
    }
}
