//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitMind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvent
    {
        public int userEventId { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> checkInDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
